apiVersion: v2
name: eloq-operator
description: A Helm chart for deploying EloqDB Operator to Kubernetes.
version: 1.0.0
appVersion: 1.0.0
keywords:
  - database
  - newsql
  - mariadb
  - mysql
  - redis
  - bigtable
  - cassandra
  - dynamodb
  - operator

dependencies:
  - name: cert-manager
    alias: certmanager
    repository: https://charts.jetstack.io
    condition: cert-manager.enabled
    version: ">=1.19.2"

source:
  - https://github.com/monographdb/eloq-operator

maintainers:
  - name: MonographDB Inc
    url: https://www.eloqdata.com/
