# Default values for eloq-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

timezone: UTC

## controller manager
## Note: This operator requires Go 1.24+ and includes improved cluster naming with date prefixes
controllerManager:
  # nodeSelector:
  #   eloqdata.com/node: control-plane
  serviceAccount:
    name: "eloq-operator-controller-manager"
    annotations: {}
  image:
    repository: eloqdata/eloq-operator
    tag: 1.0.1
  imagePullPolicy: Always
  ## In case the above image is pulled from a registry that requires
  ## authentication, a secret containing credentials can be added
  ## imagePullSecrets:
  ##   - secret_with_credentials_to_custom_registry
  imagePullSecrets: {}
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  healthPort: 8081
  metricPort: 8080
  ## Set `watchNamespaces` to watch the specific namespaces, otherwise the controller by default watches all
  ## MonographDBCluster in all namespaces.
  ## e.g.
  ## watchNamespaces: "N1, N2, N3"
  watchNamespaces: ""

  enableLeaderElection: true
  kubeApiQps: 100
  kubeApiBurst: 200
  ## Enable webhooks (validation/mutation)
  enableWebhooks: true
  ## Enable reconciler controllers (set to false for webhook-only mode)
  enableReconciler: true
  ## This option is used to control whether to monitor eloq-operator.
  ## If it is true, the corresponding Service, ServiceMonitor (depends on kube-prometheus-stack) will be deployed.
  enableMonitor: false
  ## This ServiceMonitor is to serve the eloq-operator's metrics
  ## controller manager.
  serviceMonitor:
    release: kube-prometheus-stack
  env: []

## Setting keepCrds to false will delete CRDs after helm uninstall the release
keepCrds: true

cert-manager:
  # -- Install cert-manger. Set to false to use an existing cert-manager
  enabled: false
